### ISSUE TITLE
Loading previously created TH2F into python/matplotlib

### ISSUE THREAD

**Issue by malbergo** [pieterdavid/mplbplot#4]
Hi there,

This is less of an issue and more of a question. I have some physics simulation that runs many events. I make 2D images of where energy is deposited in a detector over some x,y 2D histogram. Currently I make this histogram in python using all the x,y and energy data from all the particles in the detection, but this makes for very large ROOT files. I'd much prefer to just save the TH2F histograms of this binned data (energy binned along x,y) rather than the ntuples for this purpose. 

Is it possible to use mplbplot to merely load the histograms directly from the ROOT file so that I can plot the data stored in the histogram (which will be much less data than the ntuple because of the binning) in python using matplotlib?

Thanks for your guidance.

**Comment by pieterdavid** [comment]
Thanks for your interest! If I understand your question correctly, it boils down to whether TH2F histograms are supported. The wrappers and basic visualisations ("COL(Z)" and contour lines/fills) are there, the 3D options (surface, lego etc.) from ROOT not (mostly because I did not need them yet). I added some examples in [this notebook](https://gist.github.com/pieterdavid/ddb47786c59a4db7794f3a66b2588cc8#file-ex_th2-ipynb). The interpolation settings for contours may need a bit of finetuning (the defaults look different in matplotlib and ROOT).

**Comment by malbergo** [comment]
Thanks for your response! Though I might not have been very clear. I load a ROOT file that already has a hist in it. In these examples you make a hist from scratch, fill it, then plot it. I'm just trying to figure out how to load a "pre-made" hist that it's in a root file and display it in python/convert the data from that hist to a numpy array or such. Is there a way of doing this?

**Comment by pieterdavid** [comment]
That is only to avoid passing input files to the examples, there is nothing special with those histograms, you can just as well load them from a file, e.g.
```python
import ROOT
from matplotlib import pyplot as plt
import mplbplot.decorateAxes

f = ROOT.TFile.Open("histos.root")
h2 = f2.Get("h2") ## a TH2F

fig,ax = plt.subplots(num="COLZ")
mp = ax.rpcolor(h2, cmap="afmhot", vmin=0.)
fig.colorbar(mp, ax=ax)
```

**Comment by malbergo** [comment]
Ah, thanks kindly!
